### ISSUE TITLE
/openshift/insights/advisor wrongly redirects to /openshift/insights/sample

### ISSUE THREAD

**Issue by gkarat** [RedHatInsights/ocp-advisor-frontend#7]
I've also run into one issue I haven't found a way how to solve yet: when opening `/beta/openshift/insights/advisor` it redirects you to `/beta/openshift/insights/sample` instead of desired `/beta/openshift/insights/advisor/sample`.

_Originally posted by @gkarat in https://github.com/RedHatInsights/ocp-advisor-frontend/issues/6#issuecomment-872997765_

**Comment by gkarat** [comment]
I have a gut feeling we should add `ocp-advisor` to the OCM sub-apps: https://github.com/RedHatInsights/cloud-services-config/blob/ci-beta/main.yml#L612. @AllenBW, WDYT?

**Comment by AllenBW** [comment]
@gkarat nope, its yer local route config that's driving that... sub apps are for everything we want to live under the subscriptions tab... can't find the mocks... but my recollection is we didn't want advisor under that tab group
![Screen Shot 2021-07-12 at 10 47 16 AM](https://user-images.githubusercontent.com/6640236/125308195-b3244000-e2fe-11eb-8f65-9fafd7710d44.png)

**Comment by gkarat** [comment]
Seems to be solved by https://github.com/RedHatInsights/ocp-advisor-frontend/pull/11
